name: publish to npm
on:
  push:
    tags:
      - .*
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install dependencies
        run: |
          npm ci
          npm install -g @angular/cli@6
      - name: build using angular cli
        run: |
          ng build angular-datetimerangepicker
          cp -r projects/angular-datetimerangepicker/src/styles dist/angular-datetimerangepicker
          cd dist/angular-datetimerangepicker
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
