name: publish to npm
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: install dependencies
        run: |
          npm ci
          npm install -g @angular/cli@6
      - name: build using angular cli
        run: ng build angular-datetimerangepicker
      - run: cp -r projects/angular-datetimerangepicker/src/styles dist/angular-datetimerangepicker
      - name: publish
        run: |
          cd dist/angular-datetimerangepicker
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
